### ISSUE TITLE
Panic on EBS dry run after successful attach

### ISSUE THREAD

**Issue by sevagh** [sevagh/goat#26]
```shell
[centos@ip-10-0-1-226 ~]$ goat ebs --dry
INFO[0000] Running goat for EBS
INFO[0000] WELCOME TO GOAT
INFO[0000] 1: COLLECTING EC2 INFO
INFO[0000] Establishing metadata client
INFO[0000] Retrieved metadata successfully               instance_id=i-0da5f72185babbf66
INFO[0000] Using metadata to initialize EC2 SDK client   az=us-east-1a instance_id=i-0da5f72185babbf66 region=us-east-1
INFO[0000] 2: COLLECTING EBS INFO
INFO[0000] Searching for EBS volumes
INFO[0000] Classifying EBS volumes based on tags
INFO[0000] 3: ATTACHING EBS VOLS
INFO[0000] 4: MOUNTING ATTACHED VOLS
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/sevagh/goat/commands/ebs.prepAndMountDrives(0xc420176980, 0x4, 0x971680, 0x0, 0x0, 0xc4201a2e01)
        /home/sevagh/go/src/github.com/sevagh/goat/commands/ebs/ebs.go:40 +0x133a
github.com/sevagh/goat/commands/ebs.GoatEbs(0x7a0001)
        /home/sevagh/go/src/github.com/sevagh/goat/commands/ebs/ebs.go:33 +0x2d6
main.main()
        /home/sevagh/go/src/github.com/sevagh/goat/main.go:48 +0x3a2
[centos@ip-10-0-1-226 ~]$
```

**Comment by sevagh** [comment]
wontfix
